version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app/server
      - ./client:/app/client
    command: node ./dist/app.js